### PR TITLE
Setup the filter for slides

### PR DESCRIPTION
**Pull request by lamtu1**
Create a tab two setup one for active and one for all slides.

### CODE REVIEW

**Comment by straleyb** [comment]
@lamtu1 Do we not have access to bootstrap Tabs? Or is this navigation library just something we had to hook in for it?

**Comment by lamtu1** [comment]
We do have access to Bootstrap tabs but I just build it from what I see in Scholars Archive. I was using this bootstrap as reference:

Link: https://getbootstrap.com/docs/4.0/components/navs/

It already existed in kiosk so I just use it and build the tabs like that

**Comment by straleyb** [comment]
Perfect. Just wanted to make sure. Post a quick video of the functionality and then ill approve and we can get it merged

**Comment by lamtu1** [comment]
Demo video of the Tabs
https://github.com/osulp/kiosks/assets/111306182/27b27df2-ea5a-4151-8bdb-aa456365ab1b

**Pull request merged**
