### PR TITLE
Fix the consistence layout

### PR DESCRIPTION
**Pull request by lamtu1**
Add in the layout to fixed the consistence layout on the kiosk via the upload of image and video.

### CODE REVIEW

**Comment by straleyb** [comment]
Can I get a screenshot for this? upload a few different sized pictures and have it rotate through so we can see if its all normalized

**Comment by lamtu1** [comment]
Below are some examples of imaging through the carousel:

Original image size: 1000 x 1000
Screenshot 2023-03-06 at 10 32 02 AM

Original image size: 1920 x 1080
Screenshot 2023-03-06 at 10 32 22 AM

Original image size: 500 x 300
Screenshot 2023-03-06 at 10 32 30 AM

**Comment by lamtu1** [comment]
I currently trying to fix the `button` in the carousel and will work on the `video size consistency` as well

**Comment by straleyb** [comment]
Alright ill keep an eye on this PR and when the video stuff is working/buttons are fixed then ill check it out again.

**Pull request merged**
